# Generated by Django 5.2.3 on 2025-07-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0005_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
